# Generated by Django 4.2.12 on 2024-05-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_krapivinarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ft_vector',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='article',
            name='scibert_vector',
            field=models.JSONField(default=list),
        ),
    ]
