# Generated by Django 4.2.12 on 2024-05-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_ft_vector_article_scibert_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ft_vector',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='scibert_vector',
            field=models.JSONField(default=list),
        ),
    ]
