# Generated by Django 4.2.12 on 2024-05-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_profile_ft_vector_profile_scibert_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fulltext',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
